export const WS_EVENTS = {
  PLAYER_JOINED: "PLAYER_JOINED",
  SHIPS_PLACED: "SHIPS_PLACED",
  GAME_STARTED: "GAME_STARTED",
  ATTACK_RESULT: "ATTACK_RESULT",
  GAME_OVER: "GAME_OVER",
  PLAYER_FORFEIT: "PLAYER_FORFEIT",
  PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
  PLAYER_RECONNECTED: "PLAYER_RECONNECTED",
};

export const RECONNECT_TIMEOUT_SECONDS = 10;
